version: '3.2'
networks:
  wordpress:
    ipam:
      driver: default  
services:
  wordpress:
    image: wordpress
    restart: "unless-stopped"
    networks:
      - wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      
  mysql:
    image: mysql:5.7
    restart: "unless-stopped"
    networks:
      - wordpress    
    environment:
      MYSQL_ROOT_PASSWORD: example      

