version: "3.2"
networks:
  cinetwork:
    ipam:
      driver: default
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:6.7.5
    command: -Dsonar.web.context=/sonarqube
    restart: "no"
    ports:
     - "9000:9000"
     - "9092:9092"
    networks:
      - cinetwork
    depends_on:
      - sonardb
    environment:
     - JVM_OPTS=-Xmx1024m -Xms1024 
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=mysecretpassword
  sonardb:
    container_name: sonardb
    image: postgres
    networks:
      - cinetwork
    restart: "unless-stopped"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=mysecretpassword
     
